"""Asking the rest of the library, through the existing relevance mechanism.

`answering.retrieve.search` is used **unchanged** — the brief requires it and it
is also the only way every figure measured against the one-shot path keeps
holding. The tenant and library scoping, the dense floor, `diversify`, the graph
expansion and the locator attachment all come for free, and nothing here ranks
anything.

Three decisions worth knowing before changing anything in this module.

**The source document is excluded by a post-filter, never by a filter
parameter.** `retrieve.ALLOWED_FILTERS` is an equality allowlist whose own
docstring says `tenant_id` *"is deliberately absent, and must stay absent…  Two
guards for one property, because this is the property."* That set is
security-shaped, and teaching it negation to buy one convenience is the wrong
trade. So the exclusion happens on the returned `Evidence`, which cannot widen
anybody's scope. The honest consequence is stated where it matters: the
`supported` count the probe reports **includes the source's own chunks**, so it
over-states what other documents supply, and the run's report carries the
post-filtered count beside it.

**Queries are deterministic.** They are derived by slicing the chapter's own
plan and source text, never generated by a model. Two reasons, and the second is
the one that pays: no query costs a generation call, and a retried activity
issues byte-identical query strings, which `CachedEmbedder` — the same cache
indexing uses, keyed on (model, width, task, text) — then answers for nothing. A
retry re-buys the drafting call and not the research.

**There is no planner call.** `search` takes a `Plan`, and building one costs a
generation call per query. An empty plan means `_expand` does no graph traversal
and still attaches citations and claims, which is what is actually needed here:
`answer._verify` drops any citation whose chunk has no locator, and the locator
comes from that attachment. This is the recorded fix
`test_a_vector_only_plan_still_resolves_its_locators` stands on, used on purpose.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

from ..answering.retrieve import OffCorpus, search
from ..answering.types import Evidence, Plan, Question
from ..pipeline import Spend
from .types import PURPOSES, CitedSource

log = logging.getLogger(__name__)

#: How much of a chapter's own material a query is built from. A query longer
#: than this is embedded as prose in general rather than as this subject.
QUERY_CHARS = 500

#: Salient terms a verification pass may ask about, per chapter.
MAX_TERMS = 6

#: An empty plan. Named rather than built at each call site so it is obvious
#: that no planning call is made and that this is deliberate.
NO_PLAN = Plan(intent="transform-research", template_id=None)

#: The two stages a transformation's retrieval charges under.
#:
#: **`retrieve.search` writes `ask-embedding` and it must not be left there.**
#: That name is in `ASK_COST_STAGES`, which deliberately maps to no workflow
#: stage — a question has no pipeline — so a transformation's query embeddings
#: filed under it render in the audit view beneath the trailing `stage: null`
#: heading, beside charges that belong to nobody. That is the `evidence` defect
#: exactly, which spent months doing the same thing, and it was found here the
#: same way: by running a real one and reading `cost_entry`. Worse, the
#: `COST_STAGES` entries naming these two would have been declared and written
#: by nothing at all.
STAGE_PROBE = "transform-probe"
STAGE_RESEARCH = "transform-research"

#: Capitalised runs of two or more words, and four-digit years. Deliberately
#: crude: what a verification query wants is something nameable to look up, and
#: a false positive costs one cached embedding.
#:
#: The connector alternation is what makes «Conferencia de Nicea» one term
#: rather than two, and `_TRAILING` is what stops it being «Conferencia de Nicea
#: de» — a run may pass through a connector but may not end on one.
_WORD = r"[A-ZÁÉÍÓÚÑÜ][\wÁÉÍÓÚÑÜáéíóúñü.'-]+"
_JOIN = r"(?:de|del|la|las|los|y|e|van|von|of|the|and|for)"
_PROPER = re.compile(
    rf"\b{_WORD}(?:\s+(?:{_JOIN}\s+)?{_WORD})+"
)
_TRAILING = re.compile(rf"(?:\s+{_JOIN})+$", re.IGNORECASE)
_YEAR = re.compile(r"\b(1[0-9]{3}|20[0-9]{2})\b")


@dataclass
class Research:
    """What the library gave this chapter, and what it cost to ask."""

    evidence: list[Evidence] = field(default_factory=list)
    queries_made: int = 0
    #: Queries that returned nothing above the floor. Reported rather than
    #: dropped: a chapter whose every query went off-corpus is a fact about the
    #: library, and an unmeasured count is not a zero.
    off_corpus: int = 0
    spend: list[Spend] = field(default_factory=list)
    #: The dense-floor count, before the source document was filtered out. Kept
    #: beside the filtered evidence because they measure different things and
    #: reporting only the first would over-state what the library supplies.
    supported: int = 0


def queries_for(
    purpose: str, title: str, intent: str, source_text: str, limit: int
) -> list[str]:
    """Deterministic query texts for one purpose, at most `limit` of them.

    Each purpose reads a different part of the same material, so the four do not
    collapse into one repeated query — and where two would coincide, the second
    is a cache hit rather than a second charge.
    """
    if limit <= 0:
        return []
    head = source_text[:QUERY_CHARS].strip()
    middle = source_text[len(source_text) // 2:][:QUERY_CHARS].strip()
    framing = " ".join(part for part in (title.strip(), intent.strip()) if part)

    if purpose == "context":
        # Background for what this chapter opens on.
        out = [head, framing or head]
    elif purpose == "completion":
        # What this chapter is about, framed by what it is meant to establish,
        # which is where a gap in the source would show.
        out = [f"{framing}\n\n{middle}".strip(), middle]
    elif purpose == "contradiction":
        # The middle of the chapter, where its substantive claims sit — an
        # opening is usually orientation and disagrees with nothing.
        out = [middle, f"{framing}\n\n{head}".strip()]
    elif purpose == "verification":
        out = _terms(source_text)[:limit] or [framing or head]
    else:
        out = [head]

    seen: set[str] = set()
    kept: list[str] = []
    for query in out:
        query = " ".join(query.split())
        if not query or query in seen:
            continue
        seen.add(query)
        kept.append(query)
        if len(kept) >= limit:
            break
    return kept


def _terms(text: str) -> list[str]:
    """Nameable things, in first-appearance order. Deterministic by construction."""
    found: list[str] = []
    seen: set[str] = set()
    for match in list(_PROPER.finditer(text)) + list(_YEAR.finditer(text)):
        term = " ".join(match.group(0).split()).strip(" .,;:")
        term = _TRAILING.sub("", term).strip(" .,;:")
        if len(term) < 4 or term.casefold() in seen:
            continue
        seen.add(term.casefold())
        found.append(term)
        if len(found) >= MAX_TERMS:
            break
    return found


def gather(
    settings,
    provider,
    *,
    stage: str = STAGE_RESEARCH,
    library_id: str,
    tenant_id: str,
    exclude_version_id: str,
    purposes: list[str] | tuple[str, ...],
    title: str,
    intent: str,
    source_text: str,
    allowance: int,
) -> Research:
    """Ask the library, within the allowance, and keep what is not the source.

    Purposes are visited in `PURPOSES` order rather than in the caller's, so two
    runs with the same enabled set spend the budget the same way whatever order
    a client happened to tick the boxes in.

    ``stage`` is what the query embeddings are charged under, and it is a
    parameter because the same retrieval is made twice in a run for two
    different reasons — once to size the budget, once to write a chapter — and a
    ledger that could not tell them apart would hide which half of a
    transformation's research was the expensive one.
    """
    result = Research()
    if allowance <= 0 or not purposes:
        return result

    enabled = [p for p in PURPOSES if p in set(purposes)]
    if not enabled:
        return result

    # One pass per purpose, each taking a share, then a second sweep for
    # whatever is left over: a purpose with fewer queries than its share must
    # not strand the remainder.
    per_purpose = max(1, allowance // len(enabled))
    plan: list[tuple[str, str]] = []
    for purpose in enabled:
        for query in queries_for(purpose, title, intent, source_text, per_purpose):
            plan.append((purpose, query))

    seen_chunks: set[str] = set()
    for purpose, text in plan:
        if result.queries_made >= allowance:
            break
        question = Question(
            library_id=library_id,
            text=text,
            tenant_id=tenant_id,
        )
        spend: list[Spend] = []
        supported: list[int] = []
        try:
            evidence = search(
                settings, provider, question, NO_PLAN, spend=spend, supported=supported
            )
        except OffCorpus:
            # Not an error. The library has nothing on this, which is exactly
            # what the floor is for, and the chapter is composed from its source.
            result.off_corpus += 1
            evidence = []
        except Exception as e:  # noqa: BLE001 — a chapter beats no chapter
            log.warning("research query failed (%s): %s", purpose, e)
            result.queries_made += 1
            result.spend.extend(_relabelled(spend, stage))
            continue

        result.queries_made += 1
        # Re-labelled, never passed through. See `STAGE_PROBE` above.
        result.spend.extend(_relabelled(spend, stage))
        result.supported += sum(supported)
        for item in evidence:
            # The post-filter. A document may not cite itself as an outside
            # source: its own chunks are already the chapter's material, and a
            # citation pointing back at them would tell a reader that the
            # library corroborated what only the source ever said.
            if item.version_id == exclude_version_id:
                continue
            if item.chunk_id in seen_chunks:
                continue
            seen_chunks.add(item.chunk_id)
            result.evidence.append(item)

    return result


def _relabelled(spend: list[Spend], stage: str) -> list[Spend]:
    """The same charges, filed under the stage that actually made them.

    A new `Spend` rather than a mutation: the list `retrieve.search` appended to
    is the caller's, and rewriting somebody else's object to change how it is
    filed is the kind of thing that works until a second caller shares it.
    """
    return [
        Spend(
            stage=stage,
            model=s.model,
            input_tokens=s.input_tokens,
            output_tokens=s.output_tokens,
            usd=s.usd,
        )
        for s in spend
    ]


def sources_of(citations, evidence: list[Evidence]) -> list[CitedSource]:
    """Turn verified citations into bibliography entries.

    Every field comes from the catalog or the graph by way of `Evidence`, and
    none from the model — which is what makes the closing chapter unfabricatable
    rather than merely well-instructed. A citation whose chunk is not in the
    evidence cannot occur, because `answer._verify` produced it *from* the
    evidence; the lookup is defensive, and a miss is dropped rather than filled.
    """
    by_id = {e.chunk_id: e for e in evidence}
    out: list[CitedSource] = []
    for citation in citations:
        item = by_id.get(citation.chunk_id)
        if item is None:
            continue
        out.append(
            CitedSource(
                chunk_id=citation.chunk_id,
                document_id=item.document_id,
                version_id=item.version_id,
                title=item.title,
                locator=citation.locator,
                claim=citation.claim,
            )
        )
    return out
