"""Excel extraction: the three traps real spreadsheets set.

Built as a synthetic workbook rather than a fixture file so the expectations are
readable next to the data that produces them.
"""

from __future__ import annotations

import pathlib

import pytest

from docagent.chunk import KIND_TABLE_ROW, DocRules
from docagent.extract import extract


@pytest.fixture(scope="module")
def workbook(tmp_path_factory) -> str:
    """A workbook with a merged two-row header, two tables on one sheet, and a
    formula whose cached value is written explicitly.

    openpyxl cannot evaluate formulas, so a workbook it writes has no cached
    values at all. To test the ``data_only=True`` path honestly, the formula cell
    is written with its value and a separate sheet keeps a bare formula so the
    "never opened by Excel" warning can be checked too.
    """
    import openpyxl
    from openpyxl.styles import Alignment

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Ventas 2025"

    # Merged group header spanning the two metric columns, then the real header.
    ws["A1"] = "Periodo"
    ws["B1"] = "Región"
    ws["C1"] = "Métricas"
    ws.merge_cells("C1:D1")
    ws["C1"].alignment = Alignment(horizontal="center")
    ws.append(["Mes", "Zona", "Unidades", "Ingreso"])

    rows = [
        ("Ene", "Norte", 1240, 89300),
        ("Ene", "Sur", 980, 71150),
        ("Feb", "Norte", 1310, 94100),
        ("Feb", "Sur", 1005, 73400),
        ("Mar", "Norte", 1188, 85600),
    ]
    for r in rows:
        ws.append(list(r))

    # Blank row, then a second table with its own single-row header.
    ws.append([])
    ws.append(["Concepto", "Monto"])
    ws.append(["Costos fijos", 42000])
    ws.append(["Costos variables", 31500])

    # A second sheet holding only a formula, never evaluated: this is what a
    # workbook generated by a script (and never opened) looks like.
    ws2 = wb.create_sheet("Resumen")
    ws2["A1"] = "Total"
    ws2["A2"] = "=SUM('Ventas 2025'!D3:D7)"

    path = tmp_path_factory.mktemp("xlsx") / "ventas.xlsx"
    wb.save(path)
    return str(path)


@pytest.fixture(scope="module")
def result(workbook):
    return extract(workbook, DocRules())


def test_is_structured_not_text(result):
    """A spreadsheet has no linear byte stream, so it must come back as chunks."""
    assert result.is_structured
    assert result.text is None
    assert all(c.kind == KIND_TABLE_ROW for c in result.chunks)


def test_two_tables_found_on_one_sheet(result):
    """Blank-row separation must yield two tables, each with its own header."""
    ventas = [c for c in result.chunks if c.extra["sheet"] == "Ventas 2025"]
    headers = {tuple(c.extra["columns"]) for c in ventas}
    assert len(headers) == 2, headers
    assert any("Concepto" in h for h in headers)
    assert any(any("Unidades" in col for col in h) for h in headers)


def test_merged_header_is_propagated(result):
    """The merged "Métricas" label spans C:D, so both metric columns must carry
    it — otherwise column D would be named from an empty cell."""
    ventas = [c for c in result.chunks if "Unidades" in " ".join(c.extra["columns"])]
    assert ventas
    cols = ventas[0].extra["columns"]
    metric_cols = [c for c in cols if "Unidades" in c or "Ingreso" in c]
    assert len(metric_cols) == 2
    assert all("Métricas" in c for c in metric_cols), cols


def test_header_is_repeated_inside_every_chunk(result):
    """The whole point: a window of numbers is unreadable without column names."""
    for c in result.chunks:
        first_line = c.text.splitlines()[0]
        for col in c.extra["columns"]:
            assert col in first_line, (c.cell_ref, col)


def test_cell_ref_is_truthful(workbook, result):
    """cell_ref is the spreadsheet's answer to char_span, so it must be checkable
    by reopening the workbook and reading exactly that range."""
    import openpyxl
    from openpyxl.utils import range_boundaries

    wb = openpyxl.load_workbook(workbook, data_only=True)
    for c in result.chunks:
        sheet, ref = c.cell_ref.split("!", 1)
        ws = wb[sheet]
        min_col, min_row, max_col, max_row = range_boundaries(ref)
        assert max_row - min_row + 1 == c.extra["rows"], c.cell_ref
        # Every value in the referenced range must appear in the rendered text.
        for row in ws.iter_rows(
            min_row=min_row, max_row=max_row, min_col=min_col, max_col=max_col
        ):
            for cell in row:
                if cell.value is not None:
                    assert str(cell.value).strip() in c.text, (c.cell_ref, cell.value)
    wb.close()


def test_uncached_formula_sheet_is_reported_not_silently_blank(result):
    """openpyxl cannot evaluate formulas. A sheet written by a script and never
    opened by Excel therefore has no cached values, and indexing it as blanks
    would be a silent data-loss bug — so it must be reported."""
    notes = " ".join(result.evidence.notes)
    assert "no cached values" in notes
    assert "Resumen" in notes


def test_no_formula_strings_are_indexed(result):
    """Whatever happens, the literal formula text must never reach a chunk."""
    for c in result.chunks:
        assert "=SUM(" not in c.text, c.cell_ref
